// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ListResponse.proto

package com.n4systems.fieldid.api.pub.serialization;

public final class ListResponseMessage {
  private ListResponseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.assets);
    registry.add(com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.owners);
  }
  public interface ListResponseOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ListResponse> {

    // required int32 page = 1;
    /**
     * <code>required int32 page = 1;</code>
     */
    boolean hasPage();
    /**
     * <code>required int32 page = 1;</code>
     */
    int getPage();

    // required int32 pageSize = 2;
    /**
     * <code>required int32 pageSize = 2;</code>
     */
    boolean hasPageSize();
    /**
     * <code>required int32 pageSize = 2;</code>
     */
    int getPageSize();

    // required int64 total = 3;
    /**
     * <code>required int64 total = 3;</code>
     */
    boolean hasTotal();
    /**
     * <code>required int64 total = 3;</code>
     */
    long getTotal();
  }
  /**
   * Protobuf type {@code n4systems.fieldid.api.pub.serialization.ListResponse}
   */
  public static final class ListResponse extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ListResponse> implements ListResponseOrBuilder {
    // Use ListResponse.newBuilder() to construct.
    private ListResponse(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListResponse defaultInstance;
    public static ListResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              page_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageSize_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              total_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.class, com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ListResponse> PARSER =
        new com.google.protobuf.AbstractParser<ListResponse>() {
      public ListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 page = 1;
    public static final int PAGE_FIELD_NUMBER = 1;
    private int page_;
    /**
     * <code>required int32 page = 1;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 page = 1;</code>
     */
    public int getPage() {
      return page_;
    }

    // required int32 pageSize = 2;
    public static final int PAGESIZE_FIELD_NUMBER = 2;
    private int pageSize_;
    /**
     * <code>required int32 pageSize = 2;</code>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    // required int64 total = 3;
    public static final int TOTAL_FIELD_NUMBER = 3;
    private long total_;
    /**
     * <code>required int64 total = 3;</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 total = 3;</code>
     */
    public long getTotal() {
      return total_;
    }

    private void initFields() {
      page_ = 0;
      pageSize_ = 0;
      total_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, page_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, pageSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, total_);
      }
      extensionWriter.writeUntil(2001, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, page_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, total_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code n4systems.fieldid.api.pub.serialization.ListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse, Builder> implements com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.class, com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.Builder.class);
      }

      // Construct using com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor;
      }

      public com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse getDefaultInstanceForType() {
        return com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.getDefaultInstance();
      }

      public com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse build() {
        com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse buildPartial() {
        com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse result = new com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageSize_ = pageSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.total_ = total_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse) {
          return mergeFrom((com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse other) {
        if (other == com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse.getDefaultInstance()) return this;
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPage()) {
          
          return false;
        }
        if (!hasPageSize()) {
          
          return false;
        }
        if (!hasTotal()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 page = 1;
      private int page_ ;
      /**
       * <code>required int32 page = 1;</code>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 page = 1;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>required int32 page = 1;</code>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000001;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page = 1;</code>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        onChanged();
        return this;
      }

      // required int32 pageSize = 2;
      private int pageSize_ ;
      /**
       * <code>required int32 pageSize = 2;</code>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 pageSize = 2;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>required int32 pageSize = 2;</code>
       */
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000002;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pageSize = 2;</code>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        onChanged();
        return this;
      }

      // required int64 total = 3;
      private long total_ ;
      /**
       * <code>required int64 total = 3;</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public long getTotal() {
        return total_;
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public Builder setTotal(long value) {
        bitField0_ |= 0x00000004;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        total_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:n4systems.fieldid.api.pub.serialization.ListResponse)
    }

    static {
      defaultInstance = new ListResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:n4systems.fieldid.api.pub.serialization.ListResponse)
  }

  public static final int ASSETS_FIELD_NUMBER = 1000;
  /**
   * <code>extend .n4systems.fieldid.api.pub.serialization.ListResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse,
      java.util.List<com.n4systems.fieldid.api.pub.serialization.AssetMessage.Asset>> assets = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.n4systems.fieldid.api.pub.serialization.AssetMessage.Asset.class,
        com.n4systems.fieldid.api.pub.serialization.AssetMessage.Asset.getDefaultInstance());
  public static final int OWNERS_FIELD_NUMBER = 1001;
  /**
   * <code>extend .n4systems.fieldid.api.pub.serialization.ListResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.n4systems.fieldid.api.pub.serialization.ListResponseMessage.ListResponse,
      java.util.List<com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner>> owners = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.class,
        com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ListResponse.proto\022\'n4systems.fieldid." +
      "api.pub.serialization\032\013Asset.proto\032\013Owne" +
      "r.proto\"E\n\014ListResponse\022\014\n\004page\030\001 \002(\005\022\020\n" +
      "\010pageSize\030\002 \002(\005\022\r\n\005total\030\003 \002(\003*\006\010\350\007\020\321\017:v" +
      "\n\006assets\0225.n4systems.fieldid.api.pub.ser" +
      "ialization.ListResponse\030\350\007 \003(\0132..n4syste" +
      "ms.fieldid.api.pub.serialization.Asset:v" +
      "\n\006owners\0225.n4systems.fieldid.api.pub.ser" +
      "ialization.ListResponse\030\351\007 \003(\0132..n4syste" +
      "ms.fieldid.api.pub.serialization.OwnerBB",
      "\n+com.n4systems.fieldid.api.pub.serializ" +
      "ationB\023ListResponseMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_n4systems_fieldid_api_pub_serialization_ListResponse_descriptor,
              new java.lang.String[] { "Page", "PageSize", "Total", });
          assets.internalInit(descriptor.getExtensions().get(0));
          owners.internalInit(descriptor.getExtensions().get(1));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.n4systems.fieldid.api.pub.serialization.AssetMessage.getDescriptor(),
          com.n4systems.fieldid.api.pub.serialization.OwnerMessage.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
