// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Owner.proto

package com.n4systems.fieldid.api.pub.serialization;

public final class OwnerMessage {
  private OwnerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OwnerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string parentId = 3;
    /**
     * <code>optional string parentId = 3;</code>
     */
    boolean hasParentId();
    /**
     * <code>optional string parentId = 3;</code>
     */
    java.lang.String getParentId();
    /**
     * <code>optional string parentId = 3;</code>
     */
    com.google.protobuf.ByteString
        getParentIdBytes();

    // optional string code = 4;
    /**
     * <code>optional string code = 4;</code>
     */
    boolean hasCode();
    /**
     * <code>optional string code = 4;</code>
     */
    java.lang.String getCode();
    /**
     * <code>optional string code = 4;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    // optional string notes = 5;
    /**
     * <code>optional string notes = 5;</code>
     */
    boolean hasNotes();
    /**
     * <code>optional string notes = 5;</code>
     */
    java.lang.String getNotes();
    /**
     * <code>optional string notes = 5;</code>
     */
    com.google.protobuf.ByteString
        getNotesBytes();

    // optional string streetAddress = 6;
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    boolean hasStreetAddress();
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    java.lang.String getStreetAddress();
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    com.google.protobuf.ByteString
        getStreetAddressBytes();

    // optional string city = 7;
    /**
     * <code>optional string city = 7;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 7;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 7;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    // optional string state = 8;
    /**
     * <code>optional string state = 8;</code>
     */
    boolean hasState();
    /**
     * <code>optional string state = 8;</code>
     */
    java.lang.String getState();
    /**
     * <code>optional string state = 8;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    // optional string country = 9;
    /**
     * <code>optional string country = 9;</code>
     */
    boolean hasCountry();
    /**
     * <code>optional string country = 9;</code>
     */
    java.lang.String getCountry();
    /**
     * <code>optional string country = 9;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    // optional string zip = 10;
    /**
     * <code>optional string zip = 10;</code>
     */
    boolean hasZip();
    /**
     * <code>optional string zip = 10;</code>
     */
    java.lang.String getZip();
    /**
     * <code>optional string zip = 10;</code>
     */
    com.google.protobuf.ByteString
        getZipBytes();

    // optional string phone1 = 11;
    /**
     * <code>optional string phone1 = 11;</code>
     */
    boolean hasPhone1();
    /**
     * <code>optional string phone1 = 11;</code>
     */
    java.lang.String getPhone1();
    /**
     * <code>optional string phone1 = 11;</code>
     */
    com.google.protobuf.ByteString
        getPhone1Bytes();

    // optional string phone2 = 12;
    /**
     * <code>optional string phone2 = 12;</code>
     */
    boolean hasPhone2();
    /**
     * <code>optional string phone2 = 12;</code>
     */
    java.lang.String getPhone2();
    /**
     * <code>optional string phone2 = 12;</code>
     */
    com.google.protobuf.ByteString
        getPhone2Bytes();

    // optional string fax1 = 13;
    /**
     * <code>optional string fax1 = 13;</code>
     */
    boolean hasFax1();
    /**
     * <code>optional string fax1 = 13;</code>
     */
    java.lang.String getFax1();
    /**
     * <code>optional string fax1 = 13;</code>
     */
    com.google.protobuf.ByteString
        getFax1Bytes();

    // optional string latitude = 14;
    /**
     * <code>optional string latitude = 14;</code>
     */
    boolean hasLatitude();
    /**
     * <code>optional string latitude = 14;</code>
     */
    java.lang.String getLatitude();
    /**
     * <code>optional string latitude = 14;</code>
     */
    com.google.protobuf.ByteString
        getLatitudeBytes();

    // optional string longitude = 15;
    /**
     * <code>optional string longitude = 15;</code>
     */
    boolean hasLongitude();
    /**
     * <code>optional string longitude = 15;</code>
     */
    java.lang.String getLongitude();
    /**
     * <code>optional string longitude = 15;</code>
     */
    com.google.protobuf.ByteString
        getLongitudeBytes();

    // optional string contactName = 16;
    /**
     * <code>optional string contactName = 16;</code>
     */
    boolean hasContactName();
    /**
     * <code>optional string contactName = 16;</code>
     */
    java.lang.String getContactName();
    /**
     * <code>optional string contactName = 16;</code>
     */
    com.google.protobuf.ByteString
        getContactNameBytes();

    // optional string contactEmail = 17;
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    boolean hasContactEmail();
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    java.lang.String getContactEmail();
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    com.google.protobuf.ByteString
        getContactEmailBytes();
  }
  /**
   * Protobuf type {@code n4systems.fieldid.api.pub.serialization.Owner}
   */
  public static final class Owner extends
      com.google.protobuf.GeneratedMessage
      implements OwnerOrBuilder {
    // Use Owner.newBuilder() to construct.
    private Owner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Owner(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Owner defaultInstance;
    public static Owner getDefaultInstance() {
      return defaultInstance;
    }

    public Owner getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Owner(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              parentId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              code_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              notes_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              streetAddress_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              city_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              state_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              country_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              zip_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              phone1_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              phone2_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              fax1_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              latitude_ = input.readBytes();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              longitude_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              contactName_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              contactEmail_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.internal_static_n4systems_fieldid_api_pub_serialization_Owner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.class, com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.Builder.class);
    }

    public static com.google.protobuf.Parser<Owner> PARSER =
        new com.google.protobuf.AbstractParser<Owner>() {
      public Owner parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Owner(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Owner> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string parentId = 3;
    public static final int PARENTID_FIELD_NUMBER = 3;
    private java.lang.Object parentId_;
    /**
     * <code>optional string parentId = 3;</code>
     */
    public boolean hasParentId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string parentId = 3;</code>
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string parentId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string code = 4;
    public static final int CODE_FIELD_NUMBER = 4;
    private java.lang.Object code_;
    /**
     * <code>optional string code = 4;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string code = 4;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string notes = 5;
    public static final int NOTES_FIELD_NUMBER = 5;
    private java.lang.Object notes_;
    /**
     * <code>optional string notes = 5;</code>
     */
    public boolean hasNotes() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string notes = 5;</code>
     */
    public java.lang.String getNotes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          notes_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string notes = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNotesBytes() {
      java.lang.Object ref = notes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string streetAddress = 6;
    public static final int STREETADDRESS_FIELD_NUMBER = 6;
    private java.lang.Object streetAddress_;
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    public boolean hasStreetAddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    public java.lang.String getStreetAddress() {
      java.lang.Object ref = streetAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          streetAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string streetAddress = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStreetAddressBytes() {
      java.lang.Object ref = streetAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string city = 7;
    public static final int CITY_FIELD_NUMBER = 7;
    private java.lang.Object city_;
    /**
     * <code>optional string city = 7;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string city = 7;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string state = 8;
    public static final int STATE_FIELD_NUMBER = 8;
    private java.lang.Object state_;
    /**
     * <code>optional string state = 8;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string state = 8;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          state_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string state = 8;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string country = 9;
    public static final int COUNTRY_FIELD_NUMBER = 9;
    private java.lang.Object country_;
    /**
     * <code>optional string country = 9;</code>
     */
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string country = 9;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          country_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string country = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string zip = 10;
    public static final int ZIP_FIELD_NUMBER = 10;
    private java.lang.Object zip_;
    /**
     * <code>optional string zip = 10;</code>
     */
    public boolean hasZip() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string zip = 10;</code>
     */
    public java.lang.String getZip() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string zip = 10;</code>
     */
    public com.google.protobuf.ByteString
        getZipBytes() {
      java.lang.Object ref = zip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string phone1 = 11;
    public static final int PHONE1_FIELD_NUMBER = 11;
    private java.lang.Object phone1_;
    /**
     * <code>optional string phone1 = 11;</code>
     */
    public boolean hasPhone1() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string phone1 = 11;</code>
     */
    public java.lang.String getPhone1() {
      java.lang.Object ref = phone1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone1 = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPhone1Bytes() {
      java.lang.Object ref = phone1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string phone2 = 12;
    public static final int PHONE2_FIELD_NUMBER = 12;
    private java.lang.Object phone2_;
    /**
     * <code>optional string phone2 = 12;</code>
     */
    public boolean hasPhone2() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string phone2 = 12;</code>
     */
    public java.lang.String getPhone2() {
      java.lang.Object ref = phone2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          phone2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string phone2 = 12;</code>
     */
    public com.google.protobuf.ByteString
        getPhone2Bytes() {
      java.lang.Object ref = phone2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string fax1 = 13;
    public static final int FAX1_FIELD_NUMBER = 13;
    private java.lang.Object fax1_;
    /**
     * <code>optional string fax1 = 13;</code>
     */
    public boolean hasFax1() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string fax1 = 13;</code>
     */
    public java.lang.String getFax1() {
      java.lang.Object ref = fax1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fax1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fax1 = 13;</code>
     */
    public com.google.protobuf.ByteString
        getFax1Bytes() {
      java.lang.Object ref = fax1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fax1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string latitude = 14;
    public static final int LATITUDE_FIELD_NUMBER = 14;
    private java.lang.Object latitude_;
    /**
     * <code>optional string latitude = 14;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string latitude = 14;</code>
     */
    public java.lang.String getLatitude() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          latitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string latitude = 14;</code>
     */
    public com.google.protobuf.ByteString
        getLatitudeBytes() {
      java.lang.Object ref = latitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        latitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string longitude = 15;
    public static final int LONGITUDE_FIELD_NUMBER = 15;
    private java.lang.Object longitude_;
    /**
     * <code>optional string longitude = 15;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string longitude = 15;</code>
     */
    public java.lang.String getLongitude() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          longitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string longitude = 15;</code>
     */
    public com.google.protobuf.ByteString
        getLongitudeBytes() {
      java.lang.Object ref = longitude_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string contactName = 16;
    public static final int CONTACTNAME_FIELD_NUMBER = 16;
    private java.lang.Object contactName_;
    /**
     * <code>optional string contactName = 16;</code>
     */
    public boolean hasContactName() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string contactName = 16;</code>
     */
    public java.lang.String getContactName() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contactName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contactName = 16;</code>
     */
    public com.google.protobuf.ByteString
        getContactNameBytes() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string contactEmail = 17;
    public static final int CONTACTEMAIL_FIELD_NUMBER = 17;
    private java.lang.Object contactEmail_;
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    public boolean hasContactEmail() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    public java.lang.String getContactEmail() {
      java.lang.Object ref = contactEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contactEmail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contactEmail = 17;</code>
     */
    public com.google.protobuf.ByteString
        getContactEmailBytes() {
      java.lang.Object ref = contactEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      parentId_ = "";
      code_ = "";
      notes_ = "";
      streetAddress_ = "";
      city_ = "";
      state_ = "";
      country_ = "";
      zip_ = "";
      phone1_ = "";
      phone2_ = "";
      fax1_ = "";
      latitude_ = "";
      longitude_ = "";
      contactName_ = "";
      contactEmail_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getParentIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNotesBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStreetAddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getCityBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getStateBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCountryBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getZipBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getPhone1Bytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getPhone2Bytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getFax1Bytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getLatitudeBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getLongitudeBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getContactNameBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getContactEmailBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getParentIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCodeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNotesBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStreetAddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCityBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getStateBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCountryBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getZipBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPhone1Bytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getPhone2Bytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getFax1Bytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getLatitudeBytes());
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getLongitudeBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getContactNameBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getContactEmailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code n4systems.fieldid.api.pub.serialization.Owner}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.n4systems.fieldid.api.pub.serialization.OwnerMessage.OwnerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.internal_static_n4systems_fieldid_api_pub_serialization_Owner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.class, com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.Builder.class);
      }

      // Construct using com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        parentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        notes_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        streetAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        state_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        country_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        zip_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        phone1_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        phone2_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        fax1_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        latitude_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        longitude_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        contactName_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        contactEmail_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor;
      }

      public com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner getDefaultInstanceForType() {
        return com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.getDefaultInstance();
      }

      public com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner build() {
        com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner buildPartial() {
        com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner result = new com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.parentId_ = parentId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.notes_ = notes_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.streetAddress_ = streetAddress_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.country_ = country_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.zip_ = zip_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.phone1_ = phone1_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.phone2_ = phone2_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.fax1_ = fax1_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.contactName_ = contactName_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.contactEmail_ = contactEmail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner) {
          return mergeFrom((com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner other) {
        if (other == com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasParentId()) {
          bitField0_ |= 0x00000004;
          parentId_ = other.parentId_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000008;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasNotes()) {
          bitField0_ |= 0x00000010;
          notes_ = other.notes_;
          onChanged();
        }
        if (other.hasStreetAddress()) {
          bitField0_ |= 0x00000020;
          streetAddress_ = other.streetAddress_;
          onChanged();
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000040;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasState()) {
          bitField0_ |= 0x00000080;
          state_ = other.state_;
          onChanged();
        }
        if (other.hasCountry()) {
          bitField0_ |= 0x00000100;
          country_ = other.country_;
          onChanged();
        }
        if (other.hasZip()) {
          bitField0_ |= 0x00000200;
          zip_ = other.zip_;
          onChanged();
        }
        if (other.hasPhone1()) {
          bitField0_ |= 0x00000400;
          phone1_ = other.phone1_;
          onChanged();
        }
        if (other.hasPhone2()) {
          bitField0_ |= 0x00000800;
          phone2_ = other.phone2_;
          onChanged();
        }
        if (other.hasFax1()) {
          bitField0_ |= 0x00001000;
          fax1_ = other.fax1_;
          onChanged();
        }
        if (other.hasLatitude()) {
          bitField0_ |= 0x00002000;
          latitude_ = other.latitude_;
          onChanged();
        }
        if (other.hasLongitude()) {
          bitField0_ |= 0x00004000;
          longitude_ = other.longitude_;
          onChanged();
        }
        if (other.hasContactName()) {
          bitField0_ |= 0x00008000;
          contactName_ = other.contactName_;
          onChanged();
        }
        if (other.hasContactEmail()) {
          bitField0_ |= 0x00010000;
          contactEmail_ = other.contactEmail_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.n4systems.fieldid.api.pub.serialization.OwnerMessage.Owner) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string parentId = 3;
      private java.lang.Object parentId_ = "";
      /**
       * <code>optional string parentId = 3;</code>
       */
      public boolean hasParentId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string parentId = 3;</code>
       */
      public java.lang.String getParentId() {
        java.lang.Object ref = parentId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          parentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string parentId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParentIdBytes() {
        java.lang.Object ref = parentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string parentId = 3;</code>
       */
      public Builder setParentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentId = 3;</code>
       */
      public Builder clearParentId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parentId_ = getDefaultInstance().getParentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string parentId = 3;</code>
       */
      public Builder setParentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        parentId_ = value;
        onChanged();
        return this;
      }

      // optional string code = 4;
      private java.lang.Object code_ = "";
      /**
       * <code>optional string code = 4;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string code = 4;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string code = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string code = 4;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 4;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string code = 4;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        code_ = value;
        onChanged();
        return this;
      }

      // optional string notes = 5;
      private java.lang.Object notes_ = "";
      /**
       * <code>optional string notes = 5;</code>
       */
      public boolean hasNotes() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string notes = 5;</code>
       */
      public java.lang.String getNotes() {
        java.lang.Object ref = notes_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          notes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string notes = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNotesBytes() {
        java.lang.Object ref = notes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string notes = 5;</code>
       */
      public Builder setNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        notes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string notes = 5;</code>
       */
      public Builder clearNotes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        notes_ = getDefaultInstance().getNotes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string notes = 5;</code>
       */
      public Builder setNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        notes_ = value;
        onChanged();
        return this;
      }

      // optional string streetAddress = 6;
      private java.lang.Object streetAddress_ = "";
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public boolean hasStreetAddress() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public java.lang.String getStreetAddress() {
        java.lang.Object ref = streetAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          streetAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStreetAddressBytes() {
        java.lang.Object ref = streetAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public Builder setStreetAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        streetAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public Builder clearStreetAddress() {
        bitField0_ = (bitField0_ & ~0x00000020);
        streetAddress_ = getDefaultInstance().getStreetAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string streetAddress = 6;</code>
       */
      public Builder setStreetAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        streetAddress_ = value;
        onChanged();
        return this;
      }

      // optional string city = 7;
      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 7;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string city = 7;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 7;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 7;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000040);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 7;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        city_ = value;
        onChanged();
        return this;
      }

      // optional string state = 8;
      private java.lang.Object state_ = "";
      /**
       * <code>optional string state = 8;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string state = 8;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string state = 8;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string state = 8;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 8;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000080);
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 8;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        state_ = value;
        onChanged();
        return this;
      }

      // optional string country = 9;
      private java.lang.Object country_ = "";
      /**
       * <code>optional string country = 9;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string country = 9;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string country = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string country = 9;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 9;</code>
       */
      public Builder clearCountry() {
        bitField0_ = (bitField0_ & ~0x00000100);
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <code>optional string country = 9;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        country_ = value;
        onChanged();
        return this;
      }

      // optional string zip = 10;
      private java.lang.Object zip_ = "";
      /**
       * <code>optional string zip = 10;</code>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string zip = 10;</code>
       */
      public java.lang.String getZip() {
        java.lang.Object ref = zip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          zip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zip = 10;</code>
       */
      public com.google.protobuf.ByteString
          getZipBytes() {
        java.lang.Object ref = zip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zip = 10;</code>
       */
      public Builder setZip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        zip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip = 10;</code>
       */
      public Builder clearZip() {
        bitField0_ = (bitField0_ & ~0x00000200);
        zip_ = getDefaultInstance().getZip();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip = 10;</code>
       */
      public Builder setZipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        zip_ = value;
        onChanged();
        return this;
      }

      // optional string phone1 = 11;
      private java.lang.Object phone1_ = "";
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public boolean hasPhone1() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public java.lang.String getPhone1() {
        java.lang.Object ref = phone1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phone1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public com.google.protobuf.ByteString
          getPhone1Bytes() {
        java.lang.Object ref = phone1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public Builder setPhone1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        phone1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public Builder clearPhone1() {
        bitField0_ = (bitField0_ & ~0x00000400);
        phone1_ = getDefaultInstance().getPhone1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone1 = 11;</code>
       */
      public Builder setPhone1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        phone1_ = value;
        onChanged();
        return this;
      }

      // optional string phone2 = 12;
      private java.lang.Object phone2_ = "";
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public boolean hasPhone2() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public java.lang.String getPhone2() {
        java.lang.Object ref = phone2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          phone2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPhone2Bytes() {
        java.lang.Object ref = phone2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public Builder setPhone2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        phone2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public Builder clearPhone2() {
        bitField0_ = (bitField0_ & ~0x00000800);
        phone2_ = getDefaultInstance().getPhone2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string phone2 = 12;</code>
       */
      public Builder setPhone2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        phone2_ = value;
        onChanged();
        return this;
      }

      // optional string fax1 = 13;
      private java.lang.Object fax1_ = "";
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public boolean hasFax1() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public java.lang.String getFax1() {
        java.lang.Object ref = fax1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fax1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public com.google.protobuf.ByteString
          getFax1Bytes() {
        java.lang.Object ref = fax1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fax1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public Builder setFax1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        fax1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public Builder clearFax1() {
        bitField0_ = (bitField0_ & ~0x00001000);
        fax1_ = getDefaultInstance().getFax1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fax1 = 13;</code>
       */
      public Builder setFax1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        fax1_ = value;
        onChanged();
        return this;
      }

      // optional string latitude = 14;
      private java.lang.Object latitude_ = "";
      /**
       * <code>optional string latitude = 14;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string latitude = 14;</code>
       */
      public java.lang.String getLatitude() {
        java.lang.Object ref = latitude_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          latitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string latitude = 14;</code>
       */
      public com.google.protobuf.ByteString
          getLatitudeBytes() {
        java.lang.Object ref = latitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          latitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string latitude = 14;</code>
       */
      public Builder setLatitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string latitude = 14;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00002000);
        latitude_ = getDefaultInstance().getLatitude();
        onChanged();
        return this;
      }
      /**
       * <code>optional string latitude = 14;</code>
       */
      public Builder setLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        latitude_ = value;
        onChanged();
        return this;
      }

      // optional string longitude = 15;
      private java.lang.Object longitude_ = "";
      /**
       * <code>optional string longitude = 15;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional string longitude = 15;</code>
       */
      public java.lang.String getLongitude() {
        java.lang.Object ref = longitude_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          longitude_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string longitude = 15;</code>
       */
      public com.google.protobuf.ByteString
          getLongitudeBytes() {
        java.lang.Object ref = longitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          longitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string longitude = 15;</code>
       */
      public Builder setLongitude(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string longitude = 15;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00004000);
        longitude_ = getDefaultInstance().getLongitude();
        onChanged();
        return this;
      }
      /**
       * <code>optional string longitude = 15;</code>
       */
      public Builder setLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        longitude_ = value;
        onChanged();
        return this;
      }

      // optional string contactName = 16;
      private java.lang.Object contactName_ = "";
      /**
       * <code>optional string contactName = 16;</code>
       */
      public boolean hasContactName() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public java.lang.String getContactName() {
        java.lang.Object ref = contactName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          contactName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public com.google.protobuf.ByteString
          getContactNameBytes() {
        java.lang.Object ref = contactName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder setContactName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        contactName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder clearContactName() {
        bitField0_ = (bitField0_ & ~0x00008000);
        contactName_ = getDefaultInstance().getContactName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactName = 16;</code>
       */
      public Builder setContactNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        contactName_ = value;
        onChanged();
        return this;
      }

      // optional string contactEmail = 17;
      private java.lang.Object contactEmail_ = "";
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public boolean hasContactEmail() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public java.lang.String getContactEmail() {
        java.lang.Object ref = contactEmail_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          contactEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public com.google.protobuf.ByteString
          getContactEmailBytes() {
        java.lang.Object ref = contactEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public Builder setContactEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        contactEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public Builder clearContactEmail() {
        bitField0_ = (bitField0_ & ~0x00010000);
        contactEmail_ = getDefaultInstance().getContactEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contactEmail = 17;</code>
       */
      public Builder setContactEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        contactEmail_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:n4systems.fieldid.api.pub.serialization.Owner)
    }

    static {
      defaultInstance = new Owner(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:n4systems.fieldid.api.pub.serialization.Owner)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_n4systems_fieldid_api_pub_serialization_Owner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Owner.proto\022\'n4systems.fieldid.api.pub" +
      ".serialization\032\020Extensions.proto\"\270\002\n\005Own" +
      "er\022\024\n\002id\030\001 \002(\tB\010\212\265\030\004test\022\032\n\004name\030\002 \002(\tB\014" +
      "\212\265\030\010NEW_NAME\022\020\n\010parentId\030\003 \001(\t\022\014\n\004code\030\004" +
      " \001(\t\022\r\n\005notes\030\005 \001(\t\022\025\n\rstreetAddress\030\006 \001" +
      "(\t\022\014\n\004city\030\007 \001(\t\022\r\n\005state\030\010 \001(\t\022\017\n\007count" +
      "ry\030\t \001(\t\022\013\n\003zip\030\n \001(\t\022\016\n\006phone1\030\013 \001(\t\022\016\n" +
      "\006phone2\030\014 \001(\t\022\014\n\004fax1\030\r \001(\t\022\020\n\010latitude\030" +
      "\016 \001(\t\022\021\n\tlongitude\030\017 \001(\t\022\023\n\013contactName\030" +
      "\020 \001(\t\022\024\n\014contactEmail\030\021 \001(\tB;\n+com.n4sys",
      "tems.fieldid.api.pub.serializationB\014Owne" +
      "rMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_n4systems_fieldid_api_pub_serialization_Owner_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_n4systems_fieldid_api_pub_serialization_Owner_descriptor,
              new java.lang.String[] { "Id", "Name", "ParentId", "Code", "Notes", "StreetAddress", "City", "State", "Country", "Zip", "Phone1", "Phone2", "Fax1", "Latitude", "Longitude", "ContactName", "ContactEmail", });
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(com.n4systems.fieldid.api.pub.serialization.Extensions.serializedName);
          registry.add(com.n4systems.fieldid.api.pub.serialization.Extensions.serializedName);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.n4systems.fieldid.api.pub.serialization.Extensions.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
