// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestMessages.proto

package com.n4systems.fieldid.api.pub.serialization;

public final class TestMessages {
  private TestMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TestSimpleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:n4systems.fieldid.api.pub.serialization.TestSimpleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double double_field = 1;</code>
     */
    boolean hasDoubleField();
    /**
     * <code>optional double double_field = 1;</code>
     */
    double getDoubleField();

    /**
     * <code>optional float float_field = 2;</code>
     */
    boolean hasFloatField();
    /**
     * <code>optional float float_field = 2;</code>
     */
    float getFloatField();

    /**
     * <code>optional int32 int32_field = 3;</code>
     */
    boolean hasInt32Field();
    /**
     * <code>optional int32 int32_field = 3;</code>
     */
    int getInt32Field();

    /**
     * <code>optional int64 int64_field = 4;</code>
     */
    boolean hasInt64Field();
    /**
     * <code>optional int64 int64_field = 4;</code>
     */
    long getInt64Field();

    /**
     * <code>optional uint32 uint32_field = 5;</code>
     */
    boolean hasUint32Field();
    /**
     * <code>optional uint32 uint32_field = 5;</code>
     */
    int getUint32Field();

    /**
     * <code>optional uint64 uint64_field = 6;</code>
     */
    boolean hasUint64Field();
    /**
     * <code>optional uint64 uint64_field = 6;</code>
     */
    long getUint64Field();

    /**
     * <code>optional sint32 sint32_field = 7;</code>
     */
    boolean hasSint32Field();
    /**
     * <code>optional sint32 sint32_field = 7;</code>
     */
    int getSint32Field();

    /**
     * <code>optional sint64 sint64_field = 8;</code>
     */
    boolean hasSint64Field();
    /**
     * <code>optional sint64 sint64_field = 8;</code>
     */
    long getSint64Field();

    /**
     * <code>optional fixed32 fixed32_field = 9;</code>
     */
    boolean hasFixed32Field();
    /**
     * <code>optional fixed32 fixed32_field = 9;</code>
     */
    int getFixed32Field();

    /**
     * <code>optional fixed64 fixed64_field = 10;</code>
     */
    boolean hasFixed64Field();
    /**
     * <code>optional fixed64 fixed64_field = 10;</code>
     */
    long getFixed64Field();

    /**
     * <code>optional sfixed32 sfixed32_field = 11;</code>
     */
    boolean hasSfixed32Field();
    /**
     * <code>optional sfixed32 sfixed32_field = 11;</code>
     */
    int getSfixed32Field();

    /**
     * <code>optional sfixed64 sfixed64_field = 12;</code>
     */
    boolean hasSfixed64Field();
    /**
     * <code>optional sfixed64 sfixed64_field = 12;</code>
     */
    long getSfixed64Field();

    /**
     * <code>optional bool bool_field = 13;</code>
     */
    boolean hasBoolField();
    /**
     * <code>optional bool bool_field = 13;</code>
     */
    boolean getBoolField();

    /**
     * <code>optional string string_field = 14;</code>
     */
    boolean hasStringField();
    /**
     * <code>optional string string_field = 14;</code>
     */
    java.lang.String getStringField();
    /**
     * <code>optional string string_field = 14;</code>
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();
  }
  /**
   * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestSimpleMessage}
   */
  public static final class TestSimpleMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:n4systems.fieldid.api.pub.serialization.TestSimpleMessage)
      TestSimpleMessageOrBuilder {
    // Use TestSimpleMessage.newBuilder() to construct.
    private TestSimpleMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestSimpleMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestSimpleMessage defaultInstance;
    public static TestSimpleMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestSimpleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestSimpleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              doubleField_ = input.readDouble();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              floatField_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int32Field_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              int64Field_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              uint32Field_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              uint64Field_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sint32Field_ = input.readSInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sint64Field_ = input.readSInt64();
              break;
            }
            case 77: {
              bitField0_ |= 0x00000100;
              fixed32Field_ = input.readFixed32();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              fixed64Field_ = input.readFixed64();
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              sfixed32Field_ = input.readSFixed32();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000800;
              sfixed64Field_ = input.readSFixed64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              boolField_ = input.readBool();
              break;
            }
            case 114: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00002000;
              stringField_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestSimpleMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestSimpleMessage>() {
      public TestSimpleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestSimpleMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestSimpleMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DOUBLE_FIELD_FIELD_NUMBER = 1;
    private double doubleField_;
    /**
     * <code>optional double double_field = 1;</code>
     */
    public boolean hasDoubleField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double double_field = 1;</code>
     */
    public double getDoubleField() {
      return doubleField_;
    }

    public static final int FLOAT_FIELD_FIELD_NUMBER = 2;
    private float floatField_;
    /**
     * <code>optional float float_field = 2;</code>
     */
    public boolean hasFloatField() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float float_field = 2;</code>
     */
    public float getFloatField() {
      return floatField_;
    }

    public static final int INT32_FIELD_FIELD_NUMBER = 3;
    private int int32Field_;
    /**
     * <code>optional int32 int32_field = 3;</code>
     */
    public boolean hasInt32Field() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 int32_field = 3;</code>
     */
    public int getInt32Field() {
      return int32Field_;
    }

    public static final int INT64_FIELD_FIELD_NUMBER = 4;
    private long int64Field_;
    /**
     * <code>optional int64 int64_field = 4;</code>
     */
    public boolean hasInt64Field() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 int64_field = 4;</code>
     */
    public long getInt64Field() {
      return int64Field_;
    }

    public static final int UINT32_FIELD_FIELD_NUMBER = 5;
    private int uint32Field_;
    /**
     * <code>optional uint32 uint32_field = 5;</code>
     */
    public boolean hasUint32Field() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 uint32_field = 5;</code>
     */
    public int getUint32Field() {
      return uint32Field_;
    }

    public static final int UINT64_FIELD_FIELD_NUMBER = 6;
    private long uint64Field_;
    /**
     * <code>optional uint64 uint64_field = 6;</code>
     */
    public boolean hasUint64Field() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 uint64_field = 6;</code>
     */
    public long getUint64Field() {
      return uint64Field_;
    }

    public static final int SINT32_FIELD_FIELD_NUMBER = 7;
    private int sint32Field_;
    /**
     * <code>optional sint32 sint32_field = 7;</code>
     */
    public boolean hasSint32Field() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional sint32 sint32_field = 7;</code>
     */
    public int getSint32Field() {
      return sint32Field_;
    }

    public static final int SINT64_FIELD_FIELD_NUMBER = 8;
    private long sint64Field_;
    /**
     * <code>optional sint64 sint64_field = 8;</code>
     */
    public boolean hasSint64Field() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional sint64 sint64_field = 8;</code>
     */
    public long getSint64Field() {
      return sint64Field_;
    }

    public static final int FIXED32_FIELD_FIELD_NUMBER = 9;
    private int fixed32Field_;
    /**
     * <code>optional fixed32 fixed32_field = 9;</code>
     */
    public boolean hasFixed32Field() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional fixed32 fixed32_field = 9;</code>
     */
    public int getFixed32Field() {
      return fixed32Field_;
    }

    public static final int FIXED64_FIELD_FIELD_NUMBER = 10;
    private long fixed64Field_;
    /**
     * <code>optional fixed64 fixed64_field = 10;</code>
     */
    public boolean hasFixed64Field() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional fixed64 fixed64_field = 10;</code>
     */
    public long getFixed64Field() {
      return fixed64Field_;
    }

    public static final int SFIXED32_FIELD_FIELD_NUMBER = 11;
    private int sfixed32Field_;
    /**
     * <code>optional sfixed32 sfixed32_field = 11;</code>
     */
    public boolean hasSfixed32Field() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional sfixed32 sfixed32_field = 11;</code>
     */
    public int getSfixed32Field() {
      return sfixed32Field_;
    }

    public static final int SFIXED64_FIELD_FIELD_NUMBER = 12;
    private long sfixed64Field_;
    /**
     * <code>optional sfixed64 sfixed64_field = 12;</code>
     */
    public boolean hasSfixed64Field() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional sfixed64 sfixed64_field = 12;</code>
     */
    public long getSfixed64Field() {
      return sfixed64Field_;
    }

    public static final int BOOL_FIELD_FIELD_NUMBER = 13;
    private boolean boolField_;
    /**
     * <code>optional bool bool_field = 13;</code>
     */
    public boolean hasBoolField() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional bool bool_field = 13;</code>
     */
    public boolean getBoolField() {
      return boolField_;
    }

    public static final int STRING_FIELD_FIELD_NUMBER = 14;
    private java.lang.Object stringField_;
    /**
     * <code>optional string string_field = 14;</code>
     */
    public boolean hasStringField() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional string string_field = 14;</code>
     */
    public java.lang.String getStringField() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string string_field = 14;</code>
     */
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      doubleField_ = 0D;
      floatField_ = 0F;
      int32Field_ = 0;
      int64Field_ = 0L;
      uint32Field_ = 0;
      uint64Field_ = 0L;
      sint32Field_ = 0;
      sint64Field_ = 0L;
      fixed32Field_ = 0;
      fixed64Field_ = 0L;
      sfixed32Field_ = 0;
      sfixed64Field_ = 0L;
      boolField_ = false;
      stringField_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, doubleField_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, floatField_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, int32Field_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, int64Field_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, uint32Field_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, uint64Field_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeSInt32(7, sint32Field_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeSInt64(8, sint64Field_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeFixed32(9, fixed32Field_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFixed64(10, fixed64Field_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeSFixed32(11, sfixed32Field_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeSFixed64(12, sfixed64Field_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBool(13, boolField_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBytes(14, getStringFieldBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, doubleField_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, floatField_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int32Field_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, int64Field_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, uint32Field_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, uint64Field_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, sint32Field_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, sint64Field_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(9, fixed32Field_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, fixed64Field_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(11, sfixed32Field_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(12, sfixed64Field_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, boolField_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getStringFieldBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestSimpleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:n4systems.fieldid.api.pub.serialization.TestSimpleMessage)
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.Builder.class);
      }

      // Construct using com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        doubleField_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        floatField_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        int32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        int64Field_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        uint32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        uint64Field_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        sint32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        sint64Field_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        fixed32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        fixed64Field_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        sfixed32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        sfixed64Field_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        boolField_ = false;
        bitField0_ = (bitField0_ & ~0x00001000);
        stringField_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage getDefaultInstanceForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.getDefaultInstance();
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage build() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage buildPartial() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage result = new com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.doubleField_ = doubleField_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.floatField_ = floatField_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int32Field_ = int32Field_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.int64Field_ = int64Field_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uint32Field_ = uint32Field_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uint64Field_ = uint64Field_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.sint32Field_ = sint32Field_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sint64Field_ = sint64Field_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.fixed32Field_ = fixed32Field_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.fixed64Field_ = fixed64Field_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.sfixed32Field_ = sfixed32Field_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sfixed64Field_ = sfixed64Field_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.boolField_ = boolField_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.stringField_ = stringField_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage) {
          return mergeFrom((com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage other) {
        if (other == com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage.getDefaultInstance()) return this;
        if (other.hasDoubleField()) {
          setDoubleField(other.getDoubleField());
        }
        if (other.hasFloatField()) {
          setFloatField(other.getFloatField());
        }
        if (other.hasInt32Field()) {
          setInt32Field(other.getInt32Field());
        }
        if (other.hasInt64Field()) {
          setInt64Field(other.getInt64Field());
        }
        if (other.hasUint32Field()) {
          setUint32Field(other.getUint32Field());
        }
        if (other.hasUint64Field()) {
          setUint64Field(other.getUint64Field());
        }
        if (other.hasSint32Field()) {
          setSint32Field(other.getSint32Field());
        }
        if (other.hasSint64Field()) {
          setSint64Field(other.getSint64Field());
        }
        if (other.hasFixed32Field()) {
          setFixed32Field(other.getFixed32Field());
        }
        if (other.hasFixed64Field()) {
          setFixed64Field(other.getFixed64Field());
        }
        if (other.hasSfixed32Field()) {
          setSfixed32Field(other.getSfixed32Field());
        }
        if (other.hasSfixed64Field()) {
          setSfixed64Field(other.getSfixed64Field());
        }
        if (other.hasBoolField()) {
          setBoolField(other.getBoolField());
        }
        if (other.hasStringField()) {
          bitField0_ |= 0x00002000;
          stringField_ = other.stringField_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.n4systems.fieldid.api.pub.serialization.TestMessages.TestSimpleMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double doubleField_ ;
      /**
       * <code>optional double double_field = 1;</code>
       */
      public boolean hasDoubleField() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double double_field = 1;</code>
       */
      public double getDoubleField() {
        return doubleField_;
      }
      /**
       * <code>optional double double_field = 1;</code>
       */
      public Builder setDoubleField(double value) {
        bitField0_ |= 0x00000001;
        doubleField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double double_field = 1;</code>
       */
      public Builder clearDoubleField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        doubleField_ = 0D;
        onChanged();
        return this;
      }

      private float floatField_ ;
      /**
       * <code>optional float float_field = 2;</code>
       */
      public boolean hasFloatField() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float float_field = 2;</code>
       */
      public float getFloatField() {
        return floatField_;
      }
      /**
       * <code>optional float float_field = 2;</code>
       */
      public Builder setFloatField(float value) {
        bitField0_ |= 0x00000002;
        floatField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float float_field = 2;</code>
       */
      public Builder clearFloatField() {
        bitField0_ = (bitField0_ & ~0x00000002);
        floatField_ = 0F;
        onChanged();
        return this;
      }

      private int int32Field_ ;
      /**
       * <code>optional int32 int32_field = 3;</code>
       */
      public boolean hasInt32Field() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 int32_field = 3;</code>
       */
      public int getInt32Field() {
        return int32Field_;
      }
      /**
       * <code>optional int32 int32_field = 3;</code>
       */
      public Builder setInt32Field(int value) {
        bitField0_ |= 0x00000004;
        int32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int32_field = 3;</code>
       */
      public Builder clearInt32Field() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int32Field_ = 0;
        onChanged();
        return this;
      }

      private long int64Field_ ;
      /**
       * <code>optional int64 int64_field = 4;</code>
       */
      public boolean hasInt64Field() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 int64_field = 4;</code>
       */
      public long getInt64Field() {
        return int64Field_;
      }
      /**
       * <code>optional int64 int64_field = 4;</code>
       */
      public Builder setInt64Field(long value) {
        bitField0_ |= 0x00000008;
        int64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 int64_field = 4;</code>
       */
      public Builder clearInt64Field() {
        bitField0_ = (bitField0_ & ~0x00000008);
        int64Field_ = 0L;
        onChanged();
        return this;
      }

      private int uint32Field_ ;
      /**
       * <code>optional uint32 uint32_field = 5;</code>
       */
      public boolean hasUint32Field() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 uint32_field = 5;</code>
       */
      public int getUint32Field() {
        return uint32Field_;
      }
      /**
       * <code>optional uint32 uint32_field = 5;</code>
       */
      public Builder setUint32Field(int value) {
        bitField0_ |= 0x00000010;
        uint32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uint32_field = 5;</code>
       */
      public Builder clearUint32Field() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uint32Field_ = 0;
        onChanged();
        return this;
      }

      private long uint64Field_ ;
      /**
       * <code>optional uint64 uint64_field = 6;</code>
       */
      public boolean hasUint64Field() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 uint64_field = 6;</code>
       */
      public long getUint64Field() {
        return uint64Field_;
      }
      /**
       * <code>optional uint64 uint64_field = 6;</code>
       */
      public Builder setUint64Field(long value) {
        bitField0_ |= 0x00000020;
        uint64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 uint64_field = 6;</code>
       */
      public Builder clearUint64Field() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uint64Field_ = 0L;
        onChanged();
        return this;
      }

      private int sint32Field_ ;
      /**
       * <code>optional sint32 sint32_field = 7;</code>
       */
      public boolean hasSint32Field() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional sint32 sint32_field = 7;</code>
       */
      public int getSint32Field() {
        return sint32Field_;
      }
      /**
       * <code>optional sint32 sint32_field = 7;</code>
       */
      public Builder setSint32Field(int value) {
        bitField0_ |= 0x00000040;
        sint32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 sint32_field = 7;</code>
       */
      public Builder clearSint32Field() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sint32Field_ = 0;
        onChanged();
        return this;
      }

      private long sint64Field_ ;
      /**
       * <code>optional sint64 sint64_field = 8;</code>
       */
      public boolean hasSint64Field() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional sint64 sint64_field = 8;</code>
       */
      public long getSint64Field() {
        return sint64Field_;
      }
      /**
       * <code>optional sint64 sint64_field = 8;</code>
       */
      public Builder setSint64Field(long value) {
        bitField0_ |= 0x00000080;
        sint64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 sint64_field = 8;</code>
       */
      public Builder clearSint64Field() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sint64Field_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32Field_ ;
      /**
       * <code>optional fixed32 fixed32_field = 9;</code>
       */
      public boolean hasFixed32Field() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional fixed32 fixed32_field = 9;</code>
       */
      public int getFixed32Field() {
        return fixed32Field_;
      }
      /**
       * <code>optional fixed32 fixed32_field = 9;</code>
       */
      public Builder setFixed32Field(int value) {
        bitField0_ |= 0x00000100;
        fixed32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 fixed32_field = 9;</code>
       */
      public Builder clearFixed32Field() {
        bitField0_ = (bitField0_ & ~0x00000100);
        fixed32Field_ = 0;
        onChanged();
        return this;
      }

      private long fixed64Field_ ;
      /**
       * <code>optional fixed64 fixed64_field = 10;</code>
       */
      public boolean hasFixed64Field() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional fixed64 fixed64_field = 10;</code>
       */
      public long getFixed64Field() {
        return fixed64Field_;
      }
      /**
       * <code>optional fixed64 fixed64_field = 10;</code>
       */
      public Builder setFixed64Field(long value) {
        bitField0_ |= 0x00000200;
        fixed64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 fixed64_field = 10;</code>
       */
      public Builder clearFixed64Field() {
        bitField0_ = (bitField0_ & ~0x00000200);
        fixed64Field_ = 0L;
        onChanged();
        return this;
      }

      private int sfixed32Field_ ;
      /**
       * <code>optional sfixed32 sfixed32_field = 11;</code>
       */
      public boolean hasSfixed32Field() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional sfixed32 sfixed32_field = 11;</code>
       */
      public int getSfixed32Field() {
        return sfixed32Field_;
      }
      /**
       * <code>optional sfixed32 sfixed32_field = 11;</code>
       */
      public Builder setSfixed32Field(int value) {
        bitField0_ |= 0x00000400;
        sfixed32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed32 sfixed32_field = 11;</code>
       */
      public Builder clearSfixed32Field() {
        bitField0_ = (bitField0_ & ~0x00000400);
        sfixed32Field_ = 0;
        onChanged();
        return this;
      }

      private long sfixed64Field_ ;
      /**
       * <code>optional sfixed64 sfixed64_field = 12;</code>
       */
      public boolean hasSfixed64Field() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional sfixed64 sfixed64_field = 12;</code>
       */
      public long getSfixed64Field() {
        return sfixed64Field_;
      }
      /**
       * <code>optional sfixed64 sfixed64_field = 12;</code>
       */
      public Builder setSfixed64Field(long value) {
        bitField0_ |= 0x00000800;
        sfixed64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sfixed64 sfixed64_field = 12;</code>
       */
      public Builder clearSfixed64Field() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sfixed64Field_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolField_ ;
      /**
       * <code>optional bool bool_field = 13;</code>
       */
      public boolean hasBoolField() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional bool bool_field = 13;</code>
       */
      public boolean getBoolField() {
        return boolField_;
      }
      /**
       * <code>optional bool bool_field = 13;</code>
       */
      public Builder setBoolField(boolean value) {
        bitField0_ |= 0x00001000;
        boolField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool_field = 13;</code>
       */
      public Builder clearBoolField() {
        bitField0_ = (bitField0_ & ~0x00001000);
        boolField_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object stringField_ = "";
      /**
       * <code>optional string string_field = 14;</code>
       */
      public boolean hasStringField() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional string string_field = 14;</code>
       */
      public java.lang.String getStringField() {
        java.lang.Object ref = stringField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string string_field = 14;</code>
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        java.lang.Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string string_field = 14;</code>
       */
      public Builder setStringField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        stringField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_field = 14;</code>
       */
      public Builder clearStringField() {
        bitField0_ = (bitField0_ & ~0x00002000);
        stringField_ = getDefaultInstance().getStringField();
        onChanged();
        return this;
      }
      /**
       * <code>optional string string_field = 14;</code>
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        stringField_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:n4systems.fieldid.api.pub.serialization.TestSimpleMessage)
    }

    static {
      defaultInstance = new TestSimpleMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:n4systems.fieldid.api.pub.serialization.TestSimpleMessage)
  }

  public interface TestNestedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:n4systems.fieldid.api.pub.serialization.TestNestedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string string_field = 1;</code>
     */
    boolean hasStringField();
    /**
     * <code>required string string_field = 1;</code>
     */
    java.lang.String getStringField();
    /**
     * <code>required string string_field = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();
  }
  /**
   * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestNestedMessage}
   */
  public static final class TestNestedMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:n4systems.fieldid.api.pub.serialization.TestNestedMessage)
      TestNestedMessageOrBuilder {
    // Use TestNestedMessage.newBuilder() to construct.
    private TestNestedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestNestedMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestNestedMessage defaultInstance;
    public static TestNestedMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestNestedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestNestedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              stringField_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestNestedMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestNestedMessage>() {
      public TestNestedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestNestedMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestNestedMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRING_FIELD_FIELD_NUMBER = 1;
    private java.lang.Object stringField_;
    /**
     * <code>required string string_field = 1;</code>
     */
    public boolean hasStringField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string string_field = 1;</code>
     */
    public java.lang.String getStringField() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stringField_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string string_field = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      java.lang.Object ref = stringField_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      stringField_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStringField()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStringFieldBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStringFieldBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestNestedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:n4systems.fieldid.api.pub.serialization.TestNestedMessage)
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder.class);
      }

      // Construct using com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stringField_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage getDefaultInstanceForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance();
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage build() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage buildPartial() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage result = new com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stringField_ = stringField_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage) {
          return mergeFrom((com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage other) {
        if (other == com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance()) return this;
        if (other.hasStringField()) {
          bitField0_ |= 0x00000001;
          stringField_ = other.stringField_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStringField()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stringField_ = "";
      /**
       * <code>required string string_field = 1;</code>
       */
      public boolean hasStringField() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string string_field = 1;</code>
       */
      public java.lang.String getStringField() {
        java.lang.Object ref = stringField_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stringField_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string string_field = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        java.lang.Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string string_field = 1;</code>
       */
      public Builder setStringField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stringField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string string_field = 1;</code>
       */
      public Builder clearStringField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stringField_ = getDefaultInstance().getStringField();
        onChanged();
        return this;
      }
      /**
       * <code>required string string_field = 1;</code>
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        stringField_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:n4systems.fieldid.api.pub.serialization.TestNestedMessage)
    }

    static {
      defaultInstance = new TestNestedMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:n4systems.fieldid.api.pub.serialization.TestNestedMessage)
  }

  public interface TestContainerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:n4systems.fieldid.api.pub.serialization.TestContainerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 int32_field = 1;</code>
     */
    boolean hasInt32Field();
    /**
     * <code>required int32 int32_field = 1;</code>
     */
    int getInt32Field();

    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    boolean hasNested();
    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage getNested();
    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder getNestedOrBuilder();
  }
  /**
   * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestContainerMessage}
   */
  public static final class TestContainerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:n4systems.fieldid.api.pub.serialization.TestContainerMessage)
      TestContainerMessageOrBuilder {
    // Use TestContainerMessage.newBuilder() to construct.
    private TestContainerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestContainerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestContainerMessage defaultInstance;
    public static TestContainerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestContainerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestContainerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              int32Field_ = input.readInt32();
              break;
            }
            case 18: {
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = nested_.toBuilder();
              }
              nested_ = input.readMessage(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nested_);
                nested_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestContainerMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestContainerMessage>() {
      public TestContainerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestContainerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestContainerMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INT32_FIELD_FIELD_NUMBER = 1;
    private int int32Field_;
    /**
     * <code>required int32 int32_field = 1;</code>
     */
    public boolean hasInt32Field() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 int32_field = 1;</code>
     */
    public int getInt32Field() {
      return int32Field_;
    }

    public static final int NESTED_FIELD_NUMBER = 2;
    private com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage nested_;
    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    public boolean hasNested() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage getNested() {
      return nested_;
    }
    /**
     * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
     */
    public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder getNestedOrBuilder() {
      return nested_;
    }

    private void initFields() {
      int32Field_ = 0;
      nested_ = com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInt32Field()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasNested()) {
        if (!getNested().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, int32Field_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, nested_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, int32Field_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nested_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code n4systems.fieldid.api.pub.serialization.TestContainerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:n4systems.fieldid.api.pub.serialization.TestContainerMessage)
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.class, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.Builder.class);
      }

      // Construct using com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNestedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        int32Field_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nestedBuilder_ == null) {
          nested_ = com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance();
        } else {
          nestedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage getDefaultInstanceForType() {
        return com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.getDefaultInstance();
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage build() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage buildPartial() {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage result = new com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.int32Field_ = int32Field_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (nestedBuilder_ == null) {
          result.nested_ = nested_;
        } else {
          result.nested_ = nestedBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage) {
          return mergeFrom((com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage other) {
        if (other == com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage.getDefaultInstance()) return this;
        if (other.hasInt32Field()) {
          setInt32Field(other.getInt32Field());
        }
        if (other.hasNested()) {
          mergeNested(other.getNested());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInt32Field()) {
          
          return false;
        }
        if (hasNested()) {
          if (!getNested().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.n4systems.fieldid.api.pub.serialization.TestMessages.TestContainerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int int32Field_ ;
      /**
       * <code>required int32 int32_field = 1;</code>
       */
      public boolean hasInt32Field() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 int32_field = 1;</code>
       */
      public int getInt32Field() {
        return int32Field_;
      }
      /**
       * <code>required int32 int32_field = 1;</code>
       */
      public Builder setInt32Field(int value) {
        bitField0_ |= 0x00000001;
        int32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 int32_field = 1;</code>
       */
      public Builder clearInt32Field() {
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Field_ = 0;
        onChanged();
        return this;
      }

      private com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage nested_ = com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder> nestedBuilder_;
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public boolean hasNested() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage getNested() {
        if (nestedBuilder_ == null) {
          return nested_;
        } else {
          return nestedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public Builder setNested(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage value) {
        if (nestedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nested_ = value;
          onChanged();
        } else {
          nestedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public Builder setNested(
          com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder builderForValue) {
        if (nestedBuilder_ == null) {
          nested_ = builderForValue.build();
          onChanged();
        } else {
          nestedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public Builder mergeNested(com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage value) {
        if (nestedBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              nested_ != com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance()) {
            nested_ =
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.newBuilder(nested_).mergeFrom(value).buildPartial();
          } else {
            nested_ = value;
          }
          onChanged();
        } else {
          nestedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public Builder clearNested() {
        if (nestedBuilder_ == null) {
          nested_ = com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.getDefaultInstance();
          onChanged();
        } else {
          nestedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder getNestedBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNestedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      public com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder getNestedOrBuilder() {
        if (nestedBuilder_ != null) {
          return nestedBuilder_.getMessageOrBuilder();
        } else {
          return nested_;
        }
      }
      /**
       * <code>optional .n4systems.fieldid.api.pub.serialization.TestNestedMessage nested = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder> 
          getNestedFieldBuilder() {
        if (nestedBuilder_ == null) {
          nestedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessage.Builder, com.n4systems.fieldid.api.pub.serialization.TestMessages.TestNestedMessageOrBuilder>(
                  getNested(),
                  getParentForChildren(),
                  isClean());
          nested_ = null;
        }
        return nestedBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:n4systems.fieldid.api.pub.serialization.TestContainerMessage)
    }

    static {
      defaultInstance = new TestContainerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:n4systems.fieldid.api.pub.serialization.TestContainerMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TestMessages.proto\022\'n4systems.fieldid." +
      "api.pub.serialization\032\020Extensions.proto\"" +
      "\310\002\n\021TestSimpleMessage\022\024\n\014double_field\030\001 " +
      "\001(\001\022\023\n\013float_field\030\002 \001(\002\022\023\n\013int32_field\030" +
      "\003 \001(\005\022\023\n\013int64_field\030\004 \001(\003\022\024\n\014uint32_fie" +
      "ld\030\005 \001(\r\022\024\n\014uint64_field\030\006 \001(\004\022\024\n\014sint32" +
      "_field\030\007 \001(\021\022\024\n\014sint64_field\030\010 \001(\022\022\025\n\rfi" +
      "xed32_field\030\t \001(\007\022\025\n\rfixed64_field\030\n \001(\006" +
      "\022\026\n\016sfixed32_field\030\013 \001(\017\022\026\n\016sfixed64_fie" +
      "ld\030\014 \001(\020\022\022\n\nbool_field\030\r \001(\010\022\024\n\014string_f",
      "ield\030\016 \001(\t\")\n\021TestNestedMessage\022\024\n\014strin" +
      "g_field\030\001 \002(\t\"w\n\024TestContainerMessage\022\023\n" +
      "\013int32_field\030\001 \002(\005\022J\n\006nested\030\002 \001(\0132:.n4s" +
      "ystems.fieldid.api.pub.serialization.Tes" +
      "tNestedMessageB;\n+com.n4systems.fieldid." +
      "api.pub.serializationB\014TestMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.n4systems.fieldid.api.pub.serialization.Extensions.getDescriptor(),
        }, assigner);
    internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_n4systems_fieldid_api_pub_serialization_TestSimpleMessage_descriptor,
        new java.lang.String[] { "DoubleField", "FloatField", "Int32Field", "Int64Field", "Uint32Field", "Uint64Field", "Sint32Field", "Sint64Field", "Fixed32Field", "Fixed64Field", "Sfixed32Field", "Sfixed64Field", "BoolField", "StringField", });
    internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_n4systems_fieldid_api_pub_serialization_TestNestedMessage_descriptor,
        new java.lang.String[] { "StringField", });
    internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_n4systems_fieldid_api_pub_serialization_TestContainerMessage_descriptor,
        new java.lang.String[] { "Int32Field", "Nested", });
    com.n4systems.fieldid.api.pub.serialization.Extensions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
