package com.n4systems.fieldid.wicket.pages;

import org.apache.wicket.ajax.AjaxRequestTarget;

/**
 * Definition for an ajax link handler for the WicketLinkGeneratorComponent
 */
public abstract class WicketAjaxLinkGeneratorClickHandler extends WicketLinkGeneratorClickHandler {

    /**
     * Callback to handle the Wicket link generated by WicketLinkGeneratorComponent.
     */
    abstract public void onClick(AjaxRequestTarget target);
}
