package com.n4systems.fieldid.wicket.pages;

import java.io.Serializable;


public abstract class WicketLinkGeneratorClickHandler implements Serializable {

    /**
     * Callback to handle the Wicket link generated by WicketLinkGeneratorComponent.
     */
    abstract public void onClick();
}
