// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/kirillternovsky/Documents/web/fid-pub-ws/src/main/proto/Asset.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class Asset extends Message {

  public static final Integer DEFAULT_ID = 0;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer id;

  public Asset(Integer id) {
    this.id = id;
  }

  private Asset(Builder builder) {
    this(builder.id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Asset)) return false;
    return equals(id, ((Asset) other).id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = id != null ? id.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Asset> {

    public Integer id;

    public Builder() {
    }

    public Builder(Asset message) {
      super(message);
      if (message == null) return;
      this.id = message.id;
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    @Override
    public Asset build() {
      checkRequiredFields();
      return new Asset(this);
    }
  }
}
