// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/mfrederi/workspaces/web/web/fid-pub-ws/src/main/proto/ListResponse.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Extension;
import java.util.List;

public final class Ext_ListResponse {

  private Ext_ListResponse() {
  }

  public static final Extension<ListResponse, List<Asset>> assets = Extension
      .messageExtending(Asset.class, ListResponse.class)
      .setName("com.n4systems.fieldid.api.pub.serialization.assets")
      .setTag(1000)
      .buildRepeated();
  public static final Extension<ListResponse, List<Owner>> owners = Extension
      .messageExtending(Owner.class, ListResponse.class)
      .setName("com.n4systems.fieldid.api.pub.serialization.owners")
      .setTag(1001)
      .buildRepeated();
}
