// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/protocol//org.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Extension;
import java.util.List;

public final class Ext_org {

  private Ext_org() {
  }

  public static final Extension<ListResponse, List<OrgMessage>> list = Extension
      .messageExtending(OrgMessage.class, ListResponse.class)
      .setName("com.n4systems.fieldid.api.pub.serialization.list")
      .setTag(10)
      .buildRepeated();
}
