// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/protocol//org.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;

public final class ListMessage extends Message {

  public static final Integer DEFAULT_PAGE = 0;
  public static final Integer DEFAULT_PAGESIZE = 100;

  @ProtoField(tag = 1, type = INT32)
  public final Integer page;

  @ProtoField(tag = 2, type = INT32)
  public final Integer pageSize;

  public ListMessage(Integer page, Integer pageSize) {
    this.page = page;
    this.pageSize = pageSize;
  }

  private ListMessage(Builder builder) {
    this(builder.page, builder.pageSize);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ListMessage)) return false;
    ListMessage o = (ListMessage) other;
    return equals(page, o.page)
        && equals(pageSize, o.pageSize);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = page != null ? page.hashCode() : 0;
      result = result * 37 + (pageSize != null ? pageSize.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ListMessage> {

    public Integer page;
    public Integer pageSize;

    public Builder() {
    }

    public Builder(ListMessage message) {
      super(message);
      if (message == null) return;
      this.page = message.page;
      this.pageSize = message.pageSize;
    }

    public Builder page(Integer page) {
      this.page = page;
      return this;
    }

    public Builder pageSize(Integer pageSize) {
      this.pageSize = pageSize;
      return this;
    }

    @Override
    public ListMessage build() {
      return new ListMessage(this);
    }
  }
}
