// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/protocol//org.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TestEntityCreateMessage extends Message {

  public static final Integer DEFAULT_ENTITYCODE = 0;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer entityCode;

  public TestEntityCreateMessage(Integer entityCode) {
    this.entityCode = entityCode;
  }

  private TestEntityCreateMessage(Builder builder) {
    this(builder.entityCode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TestEntityCreateMessage)) return false;
    return equals(entityCode, ((TestEntityCreateMessage) other).entityCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = entityCode != null ? entityCode.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<TestEntityCreateMessage> {

    public Integer entityCode;

    public Builder() {
    }

    public Builder(TestEntityCreateMessage message) {
      super(message);
      if (message == null) return;
      this.entityCode = message.entityCode;
    }

    public Builder entityCode(Integer entityCode) {
      this.entityCode = entityCode;
      return this;
    }

    @Override
    public TestEntityCreateMessage build() {
      checkRequiredFields();
      return new TestEntityCreateMessage(this);
    }
  }
}
