// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: src/main/protocol//org.proto
package com.n4systems.fieldid.api.pub.serialization;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class TestEntityCreateResponse extends Message {

  public static final Integer DEFAULT_STATUS = 0;
  public static final Integer DEFAULT_ENTITYCODE = 0;

  @ProtoField(tag = 1, type = INT32, label = REQUIRED)
  public final Integer status;

  @ProtoField(tag = 2, type = INT32)
  public final Integer entityCode;

  public TestEntityCreateResponse(Integer status, Integer entityCode) {
    this.status = status;
    this.entityCode = entityCode;
  }

  private TestEntityCreateResponse(Builder builder) {
    this(builder.status, builder.entityCode);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TestEntityCreateResponse)) return false;
    TestEntityCreateResponse o = (TestEntityCreateResponse) other;
    return equals(status, o.status)
        && equals(entityCode, o.entityCode);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (entityCode != null ? entityCode.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<TestEntityCreateResponse> {

    public Integer status;
    public Integer entityCode;

    public Builder() {
    }

    public Builder(TestEntityCreateResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.entityCode = message.entityCode;
    }

    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    public Builder entityCode(Integer entityCode) {
      this.entityCode = entityCode;
      return this;
    }

    @Override
    public TestEntityCreateResponse build() {
      checkRequiredFields();
      return new TestEntityCreateResponse(this);
    }
  }
}
