CREATE TABLE IF NOT EXISTS assignment_escalation_rules (
  id bigint(21) NOT NULL AUTO_INCREMENT,
  tenant_id bigint(20) NOT NULL,
  escalate_to_user_id bigint(21) NOT NULL,
  reassign_user_id bigint(21),
  notify_assignee tinyint(1) NOT NULL,
  overdue_quantity bigint(3) NOT NULL,
  overdue_unit varchar(250) NOT NULL,
  event_id bigint(21) NOT NULL,
  event_family varchar(20) NOT NULL,
  event_due_date datetime NOT NULL,
  rule_has_run tinyint(1) NOT NULL DEFAULT 0,
  subject_text varchar(255) NOT NULL,
  custom_message_text varchar(2500),
  additional_emails varchar(5000),
  state varchar(255) NOT NULL,
  created datetime NOT NULL,
  createdby bigint(21) NOT NULL,
  modified datetime,
  modifiedby bigint(21),
  primary key(id),
  constraint fk_assignment_escalation_rules_escalate_to_user_id foreign key (escalate_to_user_id) references users(id),
  constraint fk_assignment_escalation_rules_reassign_user_id foreign key (reassign_user_id) references users(id),
  constraint fk_assignment_escalation_rules_created_by foreign key (createdby) references users(id),
  constraint fk_assignment_escalation_rules_modified_by foreign key (modifiedby) references users(id),
  constraint fk_assignment_escalation_rules_event_id foreign key (event_id) references events(id),
  constraint fk_assignment_escalation_rules_tenant_id foreign key (tenant_id) references tenants(id)
);