DROP TABLE preconfigured_devices;

CREATE TABLE preconfigured_devices (
  id bigint NOT NULL AUTO_INCREMENT,
  isolationPointSourceType varchar(2),
  device varchar(255),
  PRIMARY KEY (id)
);

INSERT INTO preconfigured_devices (isolationPointSourceType, device) VALUES
('CP',  'Control Panel'),
('M',  'Hoist Hook'),
('M',  'Arm'),
('M',  'Door'),
('M',  'Forks'),
('M',  'Body'),
('M',  'Table'),
('M',  'Rails'),
('E', 'Circuit Breaker Cover'),
('E', 'Electrical Lockout Plug'),
('E', 'Plug & Hoist Control Cover'),
('E', 'Rotary/Push Button Covers'),
('E', 'Universal Wall Switch Cover'),
('E',  'Breaker'),
('E',  'Rackout Breaker'),
('E',  'Electrical Disconnect'),
('E',  'Electrical Toggle Switch'),
('E',  'Electrical Cord'),
('E',  'Fuse'),
('E',  'Battery / UPS'),
('W', 'Adjustable Ball Valve Cover'),
('W', 'Ball Valve Cover'),
('W', 'Gate Valve Cover'),
('W', 'Wedge style Ball Valve Cover'),
('W', 'Butterfly Valve'),
('W', 'Pipe Flange'),
('W', 'Quick Disconnect'),
('V', 'Adjustable Ball Valve Cover'),
('V', 'Ball Valve Cover'),
('V', 'Gate Valve Cover'),
('V', 'Wedge style Ball Valve Cover'),
('C', 'Butterfly Valve'),
('C', 'Pipe Flange'),
('C', 'Quick Disconnect'),
('S', 'Adjustable Ball Valve Cover'),
('S', 'Ball Valve Cover'),
('S', 'Gate Valve Cover'),
('S', 'Wedge style Ball Valve Cover'),
('S', 'Butterfly Valve'),
('S', 'Pipe Flange'),
('S', 'Quick Disconnect'),
('P', 'Pneumatic Lockout'),
('P', 'Butterfly Valve'),
('P', 'Pipe Flange'),
('P', 'Quick Disconnect'),
('G', 'Pressurized Gas Valve Cover'),
('G', 'Adjustable Ball Valve Cover'),
('G', 'Ball Valve Cover'),
('G', 'Gate Valve Cover'),
('G', 'Wedge style Ball Valve Cover'),
('G', 'Butterfly Valve'),
('G', 'Stop Valve'),
('G', 'Quick Disconnect'),
('G', 'Cylinder Tank Valve'),
('G', 'Pipe Flange'),
('H', 'Butterfly Valve'),
('H', 'Pipe Flange'),
('H', 'Quick Disconnect'),
(null, 'Cable Lockout'),
(null, 'Group Lock Box'),
(null, 'Lockout Hasps'),
(null, 'Steering Wheel Cover');