DROP TABLE IF EXISTS escalation_rule_asset_linker;
DROP TABLE IF EXISTS assignment_escalation_rules;

CREATE TABLE IF NOT EXISTS assignment_escalation_rules (
  id bigint(21) NOT NULL AUTO_INCREMENT,
  tenant_id bigint(20) NOT NULL,
  escalate_to_user_id bigint(21) NOT NULL,
  reassign_user_id bigint(21),
  notify_assignee tinyint(1) NOT NULL,
  overdue_quantity bigint(20) NOT NULL,
  subject_text varchar(255) NOT NULL,
  custom_message_text varchar(2500),
  additional_emails varchar(5000),
  state varchar(255) NOT NULL,
  type varchar(10) NOT NULL,
  event_type_group_id bigint(20),
  event_type_id bigint(20),
  asset_status_id bigint(20),
  asset_type_id bigint(20),
  asset_type_group_id bigint(20),
  assigned_to_id bigint(20),
  assignee_id bigint(20),
  owner_id bigint(20),
  location varchar(255),
  predefinedlocation_id bigint(20),
  freeform_location varchar(255),
  rfid_number varchar(50),
  serial_number varchar(255),
  reference_number varchar(300),
  order_number varchar(255),
  purchase_order varchar(255),
  created datetime NOT NULL,
  createdby bigint(21) NOT NULL,
  modified datetime,
  modifiedby bigint(21),
  primary key(id),
  constraint fk_assignment_escalation_rules_escalate_to_user_id foreign key (escalate_to_user_id) references users(id),
  constraint fk_assignment_escalation_rules_reassign_user_id foreign key (reassign_user_id) references users(id),
  constraint fk_assignment_escalation_rules_event_type_group foreign key (event_type_group_id) references eventtypegroups(id),
  constraint fk_assignment_escalation_rules_event_type foreign key (event_type_id) references eventtypes(id),
  constraint fk_assignment_escalation_rules_asset_status foreign key (asset_status_id) references assetstatus(id),
  constraint fk_assignment_escalation_rules_asset_type foreign key (asset_type_id) references assettypes(id),
  constraint fk_assignment_escalation_rules_asset_type_group foreign key (asset_type_group_id) references assettypegroups(id),
  constraint fk_assignment_escalation_rules_assigned_to foreign key (assigned_to_id) references users(id),
  constraint fk_assignment_escalation_rules_assignee foreign key (assignee_id) references users(id),
  constraint fk_assignment_escalation_rules_owner foreign key (owner_id) references org_base(id),
  constraint fk_assignment_escalation_rules_location foreign key (predefinedlocation_id) references predefinedlocations(id),
  constraint fk_assignment_escalation_rules_created_by foreign key (createdby) references users(id),
  constraint fk_assignment_escalation_rules_modified_by foreign key (modifiedby) references users(id),
  constraint fk_assignment_escalation_rules_tenant_id foreign key (tenant_id) references tenants(id)
);

CREATE TABLE IF NOT EXISTS escalation_rule_asset_linker (
  id bigint(21) NOT NULL AUTO_INCREMENT,
  asset_id bigint(20) NOT NULL,
  rule_id bigint(20) NOT NULL,
  rule_has_run tinyint(1) NOT NULL DEFAULT 0,
  primary key(id),
  constraint fk_escalation_rule_asset_linker_asset foreign key (asset_id) references assets(id),
  constraint fk_escalation_rule_asset_linker_rule foreign key (rule_id) references assignment_escalation_rules(id)
);