CREATE TABLE preconfigured_energy_sources (
  id bigint NOT NULL AUTO_INCREMENT,
  isolationPointSourceType varchar(2),
  source varchar(255),
  PRIMARY KEY (id)
);

INSERT INTO preconfigured_energy_sources (isolationPointSourceType, source) VALUES
('CP',  'Control Panel'),
('M',  'Gravity'),
('M',  'Motion'),
('M',  'Rotation'),
('E',  'Electrical 120'),
('E',  'Electrical 125 VDC'),
('E',  'Electrical 208V'),
('E',  'Electrical 240V'),
('E',  'Electrical 240 VDC'),
('E',  'Electrical 277V'),
('E',  'Electrical 460V'),
('E',  'Electrical 480V'),
('E',  'Electrical 2400V'),
('E',  'Electrical 7200V'),
('W',  'Condenser Water In'),
('W',  'Condenser Water Out'),
('W',  'Water Hot In'),
('W',  'Water Hot Out'),
('W',  'Water Chilled In'),
('W',  'Water Chilled Out'),
('W',  'Water In'),
('W',  'Water Out'),
('C',  'Glycol'),
('C',  'Ammonia'),
('C',  'Chemical'),
('C',  'Oil'),
('S',  'Steam'),
('S',  'Condensate'),
('P',  'Pneumatic'),
('P',  'Pneumatic 60 PSI'),
('P',  'Pneumatic 100 PSI'),
('P',  'Pneumatic 120 PSI'),
('P',  'Pneumatic 6 bar'),
('G',  'Natural Gas'),
('G',  'Nitrogen'),
('G',  'Oxygen'),
('G',  'Propane'),
('G',  'Propylene'),
('G',  'Acetylene'),
('G',  'Carbon Dioxide'),
('G',  'Weld Gas'),
('H',  'Hydraulic'),
('H',  'Hydraulic 600 PSI'),
('H',  'Hydraulic 900 PSI'),
('H',  'Hydraulic 1200 PSI');