package com.n4systems.fieldid.migrator.migrations;

import com.n4systems.fieldid.migrator.BatchStatementExecutor;
import com.n4systems.fieldid.migrator.Migration;
import com.n4systems.fieldid.migrator.ddl.AlterTable;
import com.n4systems.fieldid.migrator.ddl.DropTable;

import java.sql.Connection;

public class M201502091710_FixMissingSchemaItems extends Migration {

	@Override
	protected void up(Connection conn) throws Exception {



		BatchStatementExecutor.create()
				.add(c -> c.createStatement().execute("UPDATE oneclick_criteria SET button_group_id = NULL WHERE button_group_id not in (select id from button_groups)"))
				.add(DropTable.named("addassethistory_infooption"))
				.add(DropTable.named("addassethistory"))
				.add(DropTable.named("jobsites"))
				.add(AlterTable.named("prioritycode")
								.modifyColumn("id", "BIGINT", true, true)
								.modifyColumn("createdby", "BIGINT")
								.modifyColumn("modifiedby", "BIGINT")
								.modifyColumn("tenant_id", "BIGINT", true)
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
								.addForeignKey("tenant_id", "tenants", "id")
				)
				.add(AlterTable.named("assetcodemapping_infooption")
								.addForeignKey("r_tenant", "tenants", "id")
				)
				.add(AlterTable.named("button_groups_buttons")
								.addPrimaryKey("button_group_id", "button_id", "orderIdx")
				)
				.add(AlterTable.named("column_mappings")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
								.addForeignKey("group_id", "column_mapping_groups", "id")
				)
				.add(AlterTable.named("criteria_trends")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
								.addForeignKey("tenant_id", "tenants", "id")
								.addForeignKey("owner_id", "org_base", "id")
								.addForeignKey("event_form_id", "eventforms", "id")
								.addForeignKey("event_id", "events", "id")
								.addForeignKey("event_type_id", "eventtypes", "id")
								.addForeignKey("performedby_id", "users", "id")
								.addForeignKey("assignee_id", "users", "id")
								.addForeignKey("assigned_group_id", "user_groups", "id")
								.addForeignKey("criteria_id", "criteria", "id")
				)
				.add(AlterTable.named("eventtypes")
								.dropColumn("legacyeventid")
				)
				.add(AlterTable.named("masterevents")
								.dropColumn("schedule_id")
								.addForeignKey("priority_id", "prioritycode", "id")
				)
				.add(AlterTable.named("notificationsettings_addresses")
								.addPrimaryKey("notificationsettings_id", "addr", "orderidx")
				)
				.add(AlterTable.named("notificationsettings_assettypes")
								.addPrimaryKey("notificationsettings_id", "assettype_id", "orderidx")
								.addForeignKey("assettype_id", "assettypes", "id")
				)
				.add(AlterTable.named("notificationsettings_eventtypes")
								.addPrimaryKey("notificationsettings_id", "eventtype_id", "orderidx")
								.addForeignKey("notificationsettings_id", "notificationsettings", "id")
				)
				.add(AlterTable.named("offline_profiles_orgs")
								.addForeignKey("organizations", "org_base", "id")
				)
				.add(AlterTable.named("oneclick_criteria")
								.addForeignKey("button_group_id", "button_groups", "id")
				)
				.add(AlterTable.named("org_extendedfeatures")
								.addPrimaryKey("org_id", "feature")
				)
				.add(AlterTable.named("orgs_place_event_types")
								.addPrimaryKey("org_id", "place_event_type_id")
				)
				.add(AlterTable.named("predefined_location_levels_levels")
								.addPrimaryKey("name", "predefined_location_levels_id", "orderidx")
				)
				.add(AlterTable.named("procedure_definitions")
								.addForeignKey("developed_by_id", "users", "id")
								.addForeignKey("approved_by_id", "users", "id")
								.addForeignKey("rejected_by_id", "users", "id")
								.addForeignKey("unpublished_by_id", "users", "id")
				)
				.add(AlterTable.named("projects_users")
								.addPrimaryKey("projects_id", "resources_id")
				)
				.add(AlterTable.named("saved_items")
								.dropColumn("procedures_id")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("saved_reports_columns")
								.addPrimaryKey("saved_report_id", "column_id", "idx")
				)
				.add(AlterTable.named("saved_searches_columns")
								.addPrimaryKey("saved_search_id", "column_id", "idx")
				)
				.add(AlterTable.named("savedreports_columns")
								.addPrimaryKey("savedreports_id", "element", "idx")
				)
				.add(AlterTable.named("savedreports_criteria")
								.addPrimaryKey("savedreports_id", "element", "mapkey")
				)
				.add(AlterTable.named("select_criteria_options")
								.addPrimaryKey("select_criteria_id", "orderidx", "selectoption")
				)
				.add(AlterTable.named("setupdatalastmoddates")
								.addPrimaryKey("tenant_id")
				)
				.add(AlterTable.named("subevents")
								.addForeignKey("asset_id", "assets", "id")
								.addForeignKey("asset_status_id", "assetstatus", "id")
				)
				.add(AlterTable.named("thing_events")
								.addForeignKey("asset_status_id", "assetstatus", "id")
								.addForeignKey("owner_id", "org_base", "id")
				)
				.add(AlterTable.named("users")
								.addForeignKey("lastRunProceduresId", "saved_procedures", "id")
				)
				.add(AlterTable.named("users_saved_items")
								.addPrimaryKey("user_id", "item_id", "orderIdx")
				)
				.add(AlterTable.named("widget_definitions")
								.addForeignKey("config_id", "widget_configurations", "id")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("active_column_mappings")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("assetattachments")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("assetstatus")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("assettypegroups")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("catalogs")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("column_layouts")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("column_mapping_groups")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("dashboard_columns")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("dashboard_layouts")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("eulas")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("eventforms")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("instructionalvideos")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("loto_settings")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("observationcount")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("observationcount_groups")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("observationcount_result")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("preconfigured_devices")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("preconfigured_energy_sources")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("predefinedlocations")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("projects")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("recurring_asset_type_events")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("recurring_loto_events")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("recurring_place_events")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("savedreports")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("scores")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("score_groups")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("send_saved_item_schedules")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("subassets")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("unitofmeasures")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("widget_configurations")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("widget_definitions")
								.addForeignKey("createdby", "users", "id")
								.addForeignKey("modifiedby", "users", "id")
				)
				.add(AlterTable.named("tenant_settings")
								.addForeignKey("modifiedby", "users", "id")
				)
				.execute(conn);
	}

}
