ALTER TABLE assettypes_assettypes ADD PRIMARY KEY(assettype_id, subtypes_id);
ALTER TABLE assettypes_fileattachments ADD PRIMARY KEY(attachments_id);
ALTER TABLE catalogs_assettypes ADD PRIMARY KEY(publishedassettypes_id);
ALTER TABLE catalogs_eventtypes ADD PRIMARY KEY(publishedeventtypes_id);
ALTER TABLE combobox_criteria_options ADD PRIMARY KEY(combobox_criteria_id, orderidx);
ALTER TABLE criteria_deficiencies ADD PRIMARY KEY(criteria_id, orderidx);
ALTER TABLE criteria_recommendations ADD PRIMARY KEY(criteria_id, orderidx);
ALTER TABLE criteriaresults_deficiencies ADD PRIMARY KEY(criteriaresults_id, deficiencies_id, orderidx);
ALTER TABLE criteriaresults_recommendations ADD PRIMARY KEY(criteriaresults_id, recommendations_id, orderidx);
ALTER TABLE criteriasections_criteria ADD PRIMARY KEY(criteria_id);
ALTER TABLE eventforms_criteriasections ADD PRIMARY KEY(sections_id);
ALTER TABLE events_fileattachments ADD PRIMARY KEY(attachments_id);
ALTER TABLE eventtypes_infofieldnames ADD PRIMARY KEY(eventtypes_id, orderidx);
ALTER TABLE eventtypes_supportedprooftests ADD PRIMARY KEY(eventtypes_id, element);
ALTER TABLE masterevents ADD PRIMARY KEY(event_id);
ALTER TABLE masterevents_subevents ADD PRIMARY KEY(subevents_event_id);
ALTER TABLE notificationsettings_addresses ADD PRIMARY KEY(notificationsettings_id, orderidx);
ALTER TABLE notificationsettings_assettypes ADD PRIMARY KEY(notificationsettings_id, assettype_id);
ALTER TABLE notificationsettings_eventtypes ADD PRIMARY KEY(notificationsettings_id, eventtype_id);
ALTER TABLE org_extendedfeatures ADD PRIMARY KEY(org_id, feature);
ALTER TABLE predefined_location_levels_levels ADD PRIMARY KEY(predefined_location_levels_id, orderidx);
ALTER TABLE projects_assets ADD PRIMARY KEY(projects_id, asset_id);
ALTER TABLE projects_fileattachments ADD PRIMARY KEY(notes_id);
ALTER TABLE projects_users ADD PRIMARY KEY(projects_id, resources_id);
ALTER TABLE saved_reports_columns ADD PRIMARY KEY(saved_report_id, idx);
ALTER TABLE saved_searches_columns ADD PRIMARY KEY(saved_search_id, idx);
ALTER TABLE savedreports_columns ADD PRIMARY KEY(savedreports_id, idx);
ALTER TABLE savedreports_criteria ADD PRIMARY KEY(savedreports_id, mapkey);
ALTER TABLE select_criteria_options ADD PRIMARY KEY(select_criteria_id, orderidx);
ALTER TABLE setupdatalastmoddates ADD PRIMARY KEY(tenant_id);
ALTER TABLE statesets_states ADD PRIMARY KEY(states_id);
ALTER TABLE subevents ADD PRIMARY KEY(event_id);
ALTER TABLE users_saved_items ADD PRIMARY KEY(item_id, orderidx);