/* Generated By:JavaCC: Do not edit this line. SimpleParserConstants.java */
package com.n4systems.services.search.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int TO = 8;
  /** RegularExpression Id. */
  int HAS = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int EXACTLY = 12;
  /** RegularExpression Id. */
  int ELLIPSIS = 13;
  /** RegularExpression Id. */
  int DASH = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int HIERARCHY_DELIMITER = 18;
  /** RegularExpression Id. */
  int GREATER_THAN = 19;
  /** RegularExpression Id. */
  int GREATER_THAN_EQUALS = 20;
  /** RegularExpression Id. */
  int LESS_THAN_EQUALS = 21;
  /** RegularExpression Id. */
  int LESS_THAN = 22;
  /** RegularExpression Id. */
  int NOT_EQUALS = 23;
  /** RegularExpression Id. */
  int TODAY = 24;
  /** RegularExpression Id. */
  int TOMORROW = 25;
  /** RegularExpression Id. */
  int YESTERDAY = 26;
  /** RegularExpression Id. */
  int SLASH_DATE = 27;
  /** RegularExpression Id. */
  int DASH_DATE = 28;
  /** RegularExpression Id. */
  int VERBOSE_DATE = 30;
  /** RegularExpression Id. */
  int FLOATING_DATE = 33;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING = 35;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 36;
  /** RegularExpression Id. */
  int NUMBER = 37;
  /** RegularExpression Id. */
  int STRING = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int InVerboseDate = 1;
  /** Lexical state. */
  int InFloatingDate = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\"and\"",
    "\"or\"",
    "\"to\"",
    "\"has\"",
    "<IS>",
    "\"in\"",
    "\"!\"",
    "<ELLIPSIS>",
    "\"-\"",
    "\"[\"",
    "\"]\"",
    "<EQUALS>",
    "\"\\\\\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\"!=\"",
    "\"today\"",
    "\"tomorrow\"",
    "\"yesterday\"",
    "<SLASH_DATE>",
    "<DASH_DATE>",
    "<token of kind 29>",
    "<VERBOSE_DATE>",
    "\" \"",
    "<token of kind 32>",
    "<FLOATING_DATE>",
    "\" \"",
    "<DOUBLE_QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<NUMBER>",
    "<STRING>",
  };

}
