development:
  adapter: mysql
  database: fieldid
  host: localhost
  username: root
  encoding: utf8

development_branch:
  adapter: mysql
  database: fieldid_branch
  host: localhost
  username: root
  encoding: utf8

minimal_security:
  adapter: mysql
  database: fieldid_minimal_security
  host: localhost
  username: root
  encoding: utf8

staging:
  adapter: mysql
  database: fieldid
  host: localhost
  username: root
  password: makemore$
  encoding: utf8
 
production:
  adapter: mysql
  database: fieldid
  host: localhost
  username: fieldid
  password: qwertyNfour^
  encoding: utf8
