

development:
  adapter: jdbcmysql
  database: fieldid
  host: localhost
  username: root
  encoding: utf8


development_branch:
  adapter: jdbcmysql
  database: fieldid_branch
  host: localhost
  username: root
  encoding: utf8

staging:
  adapter: jdbcmysql
  database: fieldid
  host: localhost
  username: root
  password: makemore$
  encoding: utf8
 
production:
  adapter: jdbcmysql
  database: fieldid
  host: localhost
  username: fieldid
  password: qwertyNfour^
  encoding: utf8
  
