old:
  adapter: jdbcpostgresql
  database: fieldid
  host: localhost
  username: fieldid-sys
  password: fieldid#9 
  encoding: utf8

development:
  adapter: jdbcmysql
  database: fieldid
  host: localhost
  username: root
  encoding: utf8

staging:
  adapter: jdbcmysql
  database: fieldid
  host: localhost
  username: root
  password: makemore$
  encoding: utf8
 
production:
  adapter: jdbcpostgresql
  database: fieldid
  host: localhost
  username: fieldid-sys
  password: fieldid#9
  encoding: utf8
  
