// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/kirillternovsky/Documents/web/fid-pub-ws/src/main/proto/descriptor.proto
package com.google.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * Describes an enum type.
 */
public final class EnumDescriptorProto extends Message {

  public static final String DEFAULT_NAME = "";
  public static final List<EnumValueDescriptorProto> DEFAULT_VALUE = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING)
  public final String name;

  @ProtoField(tag = 2, label = REPEATED)
  public final List<EnumValueDescriptorProto> value;

  @ProtoField(tag = 3)
  public final EnumOptions options;

  public EnumDescriptorProto(String name, List<EnumValueDescriptorProto> value, EnumOptions options) {
    this.name = name;
    this.value = immutableCopyOf(value);
    this.options = options;
  }

  private EnumDescriptorProto(Builder builder) {
    this(builder.name, builder.value, builder.options);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof EnumDescriptorProto)) return false;
    EnumDescriptorProto o = (EnumDescriptorProto) other;
    return equals(name, o.name)
        && equals(value, o.value)
        && equals(options, o.options);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (value != null ? value.hashCode() : 1);
      result = result * 37 + (options != null ? options.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<EnumDescriptorProto> {

    public String name;
    public List<EnumValueDescriptorProto> value;
    public EnumOptions options;

    public Builder() {
    }

    public Builder(EnumDescriptorProto message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.value = copyOf(message.value);
      this.options = message.options;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder value(List<EnumValueDescriptorProto> value) {
      this.value = checkForNulls(value);
      return this;
    }

    public Builder options(EnumOptions options) {
      this.options = options;
      return this;
    }

    @Override
    public EnumDescriptorProto build() {
      return new EnumDescriptorProto(this);
    }
  }
}
