// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/kirillternovsky/Documents/web/fid-pub-ws/src/main/proto/descriptor.proto
package com.google.protobuf;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

/**
 * Describes a service.
 */
public final class ServiceDescriptorProto extends Message {

  public static final String DEFAULT_NAME = "";
  public static final List<MethodDescriptorProto> DEFAULT_METHOD = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING)
  public final String name;

  @ProtoField(tag = 2, label = REPEATED)
  public final List<MethodDescriptorProto> method;

  @ProtoField(tag = 3)
  public final ServiceOptions options;

  public ServiceDescriptorProto(String name, List<MethodDescriptorProto> method, ServiceOptions options) {
    this.name = name;
    this.method = immutableCopyOf(method);
    this.options = options;
  }

  private ServiceDescriptorProto(Builder builder) {
    this(builder.name, builder.method, builder.options);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ServiceDescriptorProto)) return false;
    ServiceDescriptorProto o = (ServiceDescriptorProto) other;
    return equals(name, o.name)
        && equals(method, o.method)
        && equals(options, o.options);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = name != null ? name.hashCode() : 0;
      result = result * 37 + (method != null ? method.hashCode() : 1);
      result = result * 37 + (options != null ? options.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<ServiceDescriptorProto> {

    public String name;
    public List<MethodDescriptorProto> method;
    public ServiceOptions options;

    public Builder() {
    }

    public Builder(ServiceDescriptorProto message) {
      super(message);
      if (message == null) return;
      this.name = message.name;
      this.method = copyOf(message.method);
      this.options = message.options;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder method(List<MethodDescriptorProto> method) {
      this.method = checkForNulls(method);
      return this;
    }

    public Builder options(ServiceOptions options) {
      this.options = options;
      return this;
    }

    @Override
    public ServiceDescriptorProto build() {
      return new ServiceDescriptorProto(this);
    }
  }
}
